# Generated by Django 5.1 on 2024-08-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0002_signup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
        migrations.AlterModelTable(
            name='signup',
            table='signup',
        ),
    ]
